#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

OUTPUT=""
SITE="$(yq r settings.yaml site)"
LANG="$(yq r settings.yaml language)"
while getopts ":ol:s:n:" opt; do
    case "${opt}" in
        n)
            NUMBER="${OPTARG}"
            ;;
        o)
            OUTPUT=1
            ;;
        s)
            SITE="${OPTARG}"
            ;;
        l)
            LANG="${OPTARG}"
            ;;
    esac
done

function is_fetched() {
    if [ "$SITE" == "boj" ] & [ -f "${DIR}/${NUMBER}.${LANG}" ]; then
        return 0
    elif [ "$SITE" == "programmers" ] & [ -f "${DIR}/${NUMBER}.${LANG}" ]; then
        return 0
    fi

    return 1
}

function fetch() {
    case "$SITE" in
    "boj")
        case "$LANG" in
            "py")
                CODE="# https://www.acmicpc.net/problem/${NUMBER}"
                ;;
            "js")
                CODE="// https://www.acmicpc.net/problem/${NUMBER}"$'\n"use strict";';
                ;;
            esac

        echo "${CODE}" > "${DIR}/${NUMBER}.${LANG}"
        ;;
    "programmers")
        curl "https://programmers.co.kr/learn/courses/30/lessons/${NUMBER}?language=python3" \
            > "${DIR}/${NUMBER}.temp.html"
        ;;
    esac

    node load.js "${SITE}" "${NUMBER}" "${DIR}"
    code "${DIR}/${NUMBER}.${LANG}"
    rm "${DIR}/${NUMBER}.temp.html"
    cp casetest.py "${DIR}"
}

function _test() {
    case "${SITE}" in
    "boj")
        case "${LANG}" in
        "py")
            python3 "${DIR}/${NUMBER}.py" < "${DIR}/${NUMBER}.input.txt" > "${DIR}/${NUMBER}.your.txt"
            ;;
        "js")
            node "${DIR}/${NUMBER}.js" < "${DIR}/${NUMBER}.input.txt" > "${DIR}/${NUMBER}.your.txt"
            ;;
        esac
        if [[ $(git diff --no-index "${DIR}/${NUMBER}.output.txt" "${DIR}/${NUMBER}.your.txt") ]]; then
            git diff --no-index "${DIR}/${NUMBER}.output.txt" "${DIR}/${NUMBER}.your.txt";
        else
            echo 'Your answer is good for in/output samples';
        fi
        ;;
    "programmers")
        python3 "${DIR}/${NUMBER}.test.py"
        ;;
    esac
}

DIR="$(yq r settings.yaml sites."$SITE")"
cd "$(dirname "${BASH_SOURCE[0]}")"

if ! is_fetched; then
    echo "Problem ${NUMBER} is not fetched yet.";
    fetch
else
    if [ ! -z "${OUTPUT}" ]; then # output only
        case "${LANG}" in
        "py")
            python3 "${DIR}/${NUMBER}.${LANG}" < "${DIR}/${NUMBER}.input.txt"
            ;;
        "js")
            node "${DIR}/${NUMBER}.${LANG}" < "${DIR}/${NUMBER}.input.txt"
            ;;
        esac
    else
        _test
    fi
fi

